name: radio_browser_api
description: An HTTP client for Radio Browser
version: 1.0.1
homepage: https://github.com/tomassasovsky/radio-browser-api.dart.git

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  http: ^1.0.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  test: ^1.24.3
  very_good_analysis: ^5.0.0+1
